version: '3.8'

services:
  api:
    image: ${PROD_IMAGE_NAME} # Specify the image name
    container_name: ${PROD_CONTAINER_NAME} # Set the container name
    build:
      context: . # Build context is the current directory
      target: prod # Build target is 'prod'
    ports:
      - ${PROD_PORT}:${PROD_EXPOSED_PORT} # Map host port to container port
    environment:
      - NODE_ENV=production # Set environment variable NODE_ENV to 'production'
    restart: on-failure # Restart the container on failure
    stop_signal: SIGINT # Signal to send to the container when stopping
    stop_grace_period: 30s # Time to wait for the container to stop gracefully
